### ISSUE TITLE
Select/Dropdown mouseover e selected hanno background troppo chiaro

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#1]
![image](https://user-images.githubusercontent.com/2202141/220774581-7ac9ff37-00a1-4763-9619-70cbef36f62e.png)

Questo e' da user profile ma anche in admin e suppongo in tutte le select/dropdown

**Comment by achillecalegari** [comment]
Li vedo così adesso, dovrei aver fixato:
![image](https://user-images.githubusercontent.com/5371634/220787571-d971029e-9345-4203-aca1-824e8b9dab67.png)
