### ISSUE TITLE
[Mobile] border sinistro delle sottocategorie 

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#11]
![image](https://user-images.githubusercontent.com/2202141/220791182-efcf599d-9503-48e9-ac36-14f416364f6a.png)

Per vederlo direttamente, con Chrome, `CTRL+SHIFT+I` (o equivalente sul mac) e poi clicca qui:

![image](https://user-images.githubusercontent.com/2202141/220791285-b36e0c27-e6ed-4689-897f-98f16739a66a.png)

In alto, seleziona una device:

![image](https://user-images.githubusercontent.com/2202141/220791328-d6784d0a-b608-47c4-a417-c7940e943ff3.png)

Poi refresha perche' non adatta lo stile bene "al volo".

**Comment by achillecalegari** [comment]
Fatto
