### ISSUE TITLE
Reactions counter necessita' di un po' di padding

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#12]
![image](https://user-images.githubusercontent.com/2202141/220792109-1ad6c252-7925-4074-b7ce-59527a39fe87.png)

Su Mobile invece sembra a posto

![image](https://user-images.githubusercontent.com/2202141/220792226-6120f9f7-0f7d-47c5-ac17-edb5beb5e759.png)

**Comment by achillecalegari** [comment]
Vai a sapere perché, roba rotta di DIscourse stesso.
