### ISSUE TITLE
[Mobile] Tapping sull'icona delle reaction, seleziona invece l'azione a destra

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#13]
![image](https://user-images.githubusercontent.com/2202141/220792387-125d3fca-be5b-41df-9d7d-e74d22aeae61.png)

testando con il mouse (quindi no fat fingers), si vede che sta prendendo il press sul tasto di fianco

Non succede se c'e' gia' una reaction (e quindi un counter vicino visibile)

![image](https://user-images.githubusercontent.com/2202141/220792626-44ef823b-30e3-454a-a07f-0014b650d51e.png)

Per testare da un pc, vedi issue #11

**Comment by achillecalegari** [comment]
Sto provando a guardarci ma non ho ASSOLUTAMENTE idea del perché faccia così. Non ci sono div sovrapposti, sembra che venga approssimato il touch sul tasto a destra perché è un button mentre il like è un div scriptato. Non ho idea di come fixare.

**Comment by theCrius** [comment]
provo a disattivare il reaction component e vedere, sicuro e' quello che scassa la minchia

**Comment by theCrius** [comment]
Disattivato il plugin delle reaction, va tutto liscio.

Le reaction sembrano piacere parecchio ma a me quel plugin sa MOLTO di "shoddy" sinceramente.
Mi prendero' le palate di merda ma per ora lo teniamo spento. Buttaci un tag "postlaunch" in caso su sto issue e vedremo se c'e' chi chiede a gran voce ste reaction dopo la migrazione.
