### ISSUE TITLE
mouseover sulla label che indica nuovi replies ha un text color chiaro

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#15]
![image](https://user-images.githubusercontent.com/2202141/220793485-cd03443c-6b57-461a-bae8-7ea509cee8fb.png)

Quello sopra e' il default, quello sotto e' in mouseover.

Forse sarebbe meglio cambiare il background su mouseover? O comunque cambiare il font color ma in un colore che non sia giallo chiaro perche' non si vede niente su grigio 😄

**Comment by achillecalegari** [comment]
Deployato
