### ISSUE TITLE
Colori categorie (report by Nobsyde)

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#17]
> Pagina All Categories
> Colore di sfondo delle sezioni diverso dallo standard (attualmente #555d6a [–new-lightgray in :root] vs #5f6b7e
> sotto menu
> –primary-med-or-secondary-high: attualmente #646464 - più corretto #3f4754
> link sotto menu
> –primary-high: ora #a6a6a6 - o #ccc per già visitati, o #fff per nuovi
> sfondo main
> –secondary: #222222, meglio #30353f o #191919

Attuale su stage
![image](https://user-images.githubusercontent.com/2202141/220851227-05985fc9-5aac-4448-b050-89e2135a40ab.png)

Con colori "corretti" via dev console del browser
![image](https://user-images.githubusercontent.com/2202141/220851302-581a27d4-84a9-4b16-a305-8cc1a20a3a31.png)

**Comment by achillecalegari** [comment]
Corretto le subcat, ma il resto cozza di brutto imho
