### ISSUE TITLE
sidebar background color

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#18]
Probabilmente perche' inizialmente mi aveva detto Drest che la sidebar era troppo "straniante" e invece poi provando tutti la adorano.

E' perfetta imho ma andrebbe sistemato il background color forse?

![image](https://user-images.githubusercontent.com/2202141/220855264-e370ca2d-5717-43b2-8389-ffcba6a5f808.png)

Report di matsnake86 http://staging-56789.netgamers.it/t/feedback-sul-gnr-style/834967/13?u=ngi-admin

**Comment by achillecalegari** [comment]
"Tutti" non lo so, per me è angosciatamente brutta e non aggiunge niente alla navigazione che non sia già disponibile nell'altro menu utente o in navigazione classica. Messo i colori giusti comunque.

**Comment by theCrius** [comment]
Si capisco che possa non piacere a tutti, intendevo chi ha testato in questi giorni.

Si puo' nascondere comunque, cliccando sull'hamburger menu in alto
