### ISSUE TITLE
Font by google no gdpr compliant

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#20]
> non usate le font da fonts.googleapis.com non sono gdpr compliant, vi suggerisco invece di cambiarle in queste https://fonts.bunny.net/css che lo sono invece

Da _The End_

**Comment by theCrius** [comment]
credo che le potremmo anche direttamente avere caricate nel tema comunque

**Comment by achillecalegari** [comment]
io ricontrollo ma credo che al momento gfonts lo carichi discourse come libreria. IO DI SICURO ho usato solo Verdana e Tahoma come da netgamers.it attuale, se poi qualche font è rimasta in creeping dietro posso farci ma fino ad un certo punto
perché discourse ti fa scegliere la gfont da backend, temo che quella libreria sia caricata di default a prescindere

**Comment by AblabiX** [comment]
si possono cambiare

https://meta.discourse.org/t/change-the-default-font-on-your-site/21282
