### ISSUE TITLE
[iOS] Vari report su font size, scrolling, logo, etc

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#21]
per adesso questi:

http://staging-56789.netgamers.it/t/discourse-theme-feedback/834968/5?u=ngi-admin

**Comment by theCrius** [comment]
![image](https://user-images.githubusercontent.com/2202141/220861877-2a11abbc-b07b-4011-8cfd-e14bef28172f.png)

**Comment by achillecalegari** [comment]
Il logo ce lo dovete caricare voi :asd:

**Comment by theCrius** [comment]
li ho caricati ieri sera usando quelli in questo repo

adesso ricontatto chi lamentava la cosa e chiedo se hanno ancora il problema dopo che magari fanno un refresh/reinstall della pwa
