### ISSUE TITLE
Scrolling / Live Feed sui topic sballato su Safari (report from Nobyside)

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#26]
Segnati questo "alla fine di sta cosa tu odierai safari e i mac" 😆 

Quoto Nobyside:

> sono su Mac 13.2.1
problema 1: su Safari lo scrolling scatta (tipo che si blocca nell’andare su/giù, e continua a ritornare indietro), come su iOS
problema 2: su Safari tra certi reply (sembra sempre gli stessi) si creano delle div vuote, ma con una min-height esagerata, creando quello spazio vuoto degli screen
problema 3: sia su Safari che su Chrome, col semplice scrolling man mano si creano bug per cui le varie div dei reply mantengono una min-height (sbagliata), creando quindi sempre maggiori artefatti grafici

http://staging-56789.netgamers.it/t/discourse-theme-feedback/834968/57?u=ngi-admin

Video:

> lo scrolling è continuo (ho la rotella dell’mx3 lanciata a 1000). Nota che questo è chrome, nemmeno Safari
> https://i.imgur.com/YQB4ZD3.mp4

Ho chiesto un video da safari anche, appena ce l'ho lo aggiungo

**Comment by achillecalegari** [comment]
Questo è proprio un problema di discourse, me lo fa anche sul forum ufficiale. Che si fa?
