### ISSUE TITLE
Dropdown mouseover/selected colours contrasti "sbagliati"

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#28]
Mi pare fosse gia' segnalato ma non riesco a trovare l'issue tra gli aperti.

Notifiche
![image](https://user-images.githubusercontent.com/2202141/221534123-630cf49b-28f8-4279-bf25-bf7eefa8df44.png)

![image](https://user-images.githubusercontent.com/2202141/221534641-d2d4c6ce-cabf-4f3d-af93-6a7b90ab1ea6.png)

watch mode
![image](https://user-images.githubusercontent.com/2202141/221534479-8c688352-ee33-410f-9ca8-f678fe13a485.png)

"more" dalla sidebar e' ok
![image](https://user-images.githubusercontent.com/2202141/221534920-4ff94723-bfa7-4d4b-8423-025f6625ebce.png)

**Comment by achillecalegari** [comment]
Fixed
