### ISSUE TITLE
Separatore firma

### ISSUE THREAD

**Issue by achillecalegari** [achillecalegari/NGI-Theme#33]
Navigando un po' ho notato che il separatore post/firma è davvero sottilissimo e di colore molto simile allo sfondo, a volte ho difficoltà a capire dove finisce il post e dove inizia la firma (forse complice anche la pessima illuminazione della mia postazione). E' un "problema" che ho notato solo io?

**Comment by theCrius** [comment]
no, ho letto altri riportarlo. Il problema e' che e' un <hr> semplice, bisogna fare attenzione a stilizzarlo per non beccare tutti gli HR in giro :|
