### ISSUE TITLE
Font differenti tra pulsanti e non-pulsanti

### ISSUE THREAD

**Issue by theCrius** [achillecalegari/NGI-Theme#6]
Questa un po' da capire, a me non da fastidio ma non so se e' voluta o una dimenticanza.

I pulsanti sono tahoma, le categoria sono arial.

![image](https://user-images.githubusercontent.com/2202141/220776267-6653120d-fe29-4a6d-99cf-d8fad88bcf84.png)

**Comment by achillecalegari** [comment]
Fixato, rimangono da rivedere i dimensionamenti.
